app:
  name: admin-service

spring:
  profiles:
    active: development

  security:
    user:
      name: user
      password: user

    oauth2:
      client:
        registration:
          google:
            client-id: YOUR_GOOGLE_CLIENT_ID
            client-secret: YOUR_GOOGLE_CLIENT_SECRET
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            scope: openid, profile, email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/admin
    username: postgres
    password: Test@123

  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  logging:
    pattern:
      console: "%d %-5level %logger{36} : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug

  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true

  server:
    port: 8080
    error:
      whitelabel:
        enabled: false
  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: YOUR_GOOGLE_CLIENT_ID
              client-secret: YOUR_GOOGLE_CLIENT_SECRET
              scope:
                - openid
                - profile
                - email
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              user-name-attribute: sub

allowed:
  origins: http://localhost:3000 ,*

jwt:
  secret: SdhUDRppovbTl4kXC8tOo22bVIAiZEqU
  expiration: 1200000
